# Autogenerated wrapper script for SoapyMultiSDR_jll for aarch64-apple-darwin
export librtlsdrSupport

using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyMultiSDR")
JLLWrappers.@declare_library_product(librtlsdrSupport, "libMultiSDRSupport.dylib")
function __init__()
    JLLWrappers.@generate_init_header(soapysdr_jll)
    JLLWrappers.@init_library_product(
        librtlsdrSupport,
        "lib/SoapySDR/modules0.8/libMultiSDRSupport.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
