# Autogenerated wrapper script for SoapyMultiSDR_jll for i686-w64-mingw32-cxx03
export librtlsdrSupport

using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyMultiSDR")
JLLWrappers.@declare_library_product(librtlsdrSupport, "libMultiSDRSupport.dll")
function __init__()
    JLLWrappers.@generate_init_header(soapysdr_jll)
    JLLWrappers.@init_library_product(
        librtlsdrSupport,
        "bin\\libMultiSDRSupport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
